name: Build and Publish

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-push-to-docker-hub:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub
        uses: docker/build-push-action@v2
        with:
          tags: |-
            kubakdev/todo-web:latest
            kubakdev/todo-web:${{ github.sha }}
            kubakdev/todo-web:${{ github.ref_name }}
  
  push-to-digital-ocean:
    name: Pull the new images and restart docker-compose
    runs-on: ubuntu-20.04
    needs: build-and-push-to-docker-hub
    env:
     connection_string: ${{ secrets.CONNECTION_STRING }}

    steps:
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        envs: connection_string
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Go to todo directory 
          cd todo
          
          # Stop running container
          docker-compose down

          # Remove old container
          docker-compose pull

          # Run a new container from a new image
          docker-compose up -e MongoDB__ConnectionString=$connection_string


