name: Build and Publish

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub
        uses: docker/build-push-action@v2
        with:
          tags: |-
            kubakdev/todo-web:latest
            kubakdev/todo-web:${{ github.sha }}
            kubakdev/todo-web:${{ github.ref_name }}
